#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Checking styles, testing and building project before committing'

# Check Prettier standards
npm run check-format ||
(
    echo 'Prettier error';
    false;
)

# Check ESLint Standards
npm run check-lint ||
(
        echo 'ESLint error'
        false; 
)

# Check tsconfig standards
npm run check-types ||
(
    echo 'Types error'
    false;
)

# If everything passes... Now we can commit
echo 'Building'

npm run build ||
(
    echo 'Build failed'
    false;
)

# If everything passes... Now we can commit
echo 'Tests passed; committing'